version: '3.7'
services:
    test_server:
        container_name: test-server
        build:
            context: .
        volumes:
            - /app/node_modules
            - ./:/app
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - MONGO_URI=${MONGO_URI}
            - MONGO_REMOTE_URI=${MONGO_REMOTE_URI}
            - JWT_KEY=${JWT_KEY}
        ports:
            - 3000:3000
        restart: unless-stopped
